aliases:
  "Charles River IMS":
    - "IMS"
    - "Charles River Investment Management Solution"
  "InvestCloud":
    - "Invest Cloud"
  "Addepar":
    - "addepar"
  "Orion Advisor Tech":
    - "Orion"
    - "Orion Advisor Services"
