architecture_keywords:
  - api
  - openapi
  - swagger
  - sdk
  - fix
  - ibor
  - oems
  - snowflake
  - managed data
  - data platform
  - real-time
  - two-way
  - integration
  - cloud
  - postman
  - graphql
  - webhook
